name: allinone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get_it: ^4.0.2
  http: ^0.12.1
  json_serializable: ^3.3.0
  flushbar: 1.9.1
  shared_preferences: ^0.5.7
  bezier_chart: ^1.0.17+1
  math_expressions: ^2.0.0
  google_fonts: ^1.0.0
  pie_chart: ^3.1.1
  syncfusion_flutter_charts: ^18.1.48
  curved_navigation_bar: ^0.3.2
  charts_flutter: ^0.9.0
  table_calendar: ^2.2.3
  syncfusion_flutter_calendar: ^18.1.48-beta
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
